### PR TITLE
fix application deployment for maven build

### LINKED ISSUE #391: maven fails to deploy application changes
In the context of [openshift.io application deployment](https://github.com/openshiftio/openshift.io/issues/2505#issuecomment-371732158) an important [issue (#1226)](https://github.com/fabric8io/fabric8-maven-plugin/blob/master/CHANGELOG.md) has been fixed in the recent release (3.5.38) of fabric8 maven plugin (FMP).

Existing or new builds should use FMP 3.5.38 through patching the pipeline

### PR DESCRIPTION
**Pull request by hrishin**
- added patch for updating applications pom.xml to use the latest version of FMP (3.5.28) before the build begins
- passing fabric8 maven plugin version to use for build in `mvn` command

fixes #391

### CODE REVIEW

File: vars/mavenCanaryRelease.groovy [hunk 1]
```diff
@@ -9,12 +9,15 @@ def call(body) {
 
     def flow = new io.fabric8.Fabric8Commands()
     def utils = new io.fabric8.Utils()
+    def fmpPropertyName = "fabric8-maven-plugin.version"
+    def fmpPropertyValue = "3.5.38"
```
Comment (hrishin) [inline vars/mavenCanaryRelease.groovy]: @sthaha @rupalibehera @jaseemabid how can we make it parameterized instead of hardcoding it?

**Comment by jaseemabid** [comment]
This patch looks good to me, but shows some very deep flaws with our architecture and design. 

Go ahead and merge! I think the hard coded version is OK, this is not worth cleaning up.

**Comment by chmouel** [comment]
@jaseemabid If you feel like complaining on every other request  feel free to complains to the james but this is starting to get old for the team,

File: vars/mavenCanaryRelease.groovy (hunk 1 above)
Comment (rupalibehera) [reply vars/mavenCanaryRelease.groovy]: @hrishin 
https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenCanaryRelease.groovy#L15 
and then access it this way,
or if you set something like this https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/approve.groovy#L10 like a default value to some version so that you don't break any existing thing and you can use different version of fmp by just passing something like below:

In https://github.com/fabric8io/fabric8-pipeline-library/blob/master/vars/mavenCanaryRelease.groovy, you can do `def fmpPropertyValue= config.fmpPropertyValue ?: 3.5.38`
and then in Jenkisfile of a project which uses this do the below
Pass the value from Jenkinsfile 
```
        mavenCanaryRelease {
         fmpPropertyValue = '3.6'
        }
```
Then your project uses 3.6 passed via Jenkinsfile

Comment (rupalibehera) [reply vars/mavenCanaryRelease.groovy]: @hrishin , once you do the above let's see if the change works fine and then merge it.

Comment (hrishin) [reply vars/mavenCanaryRelease.groovy]: @rupalibehera that's definatelky better approach. I was wondering if we can keep these properties in pom.xml and release workflow of fmp could update the right version

File: vars/mavenCanaryRelease.groovy [hunk 2]
```diff
@@ -9,12 +9,16 @@ def call(body) {
 
     def flow = new io.fabric8.Fabric8Commands()
     def utils = new io.fabric8.Utils()
+    def fmpPropertyName = config.fmpPropertyName ?: "fabric8-maven-plugin.version"
+    def fmpPropertyValue = config.fmpPropertyValue ?: "3.5.38"
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: How about we rename it to `pomFmpProperty`and `pomFmpValue`

File: vars/mavenCanaryRelease.groovy [hunk 3]
```diff
@@ -66,3 +70,10 @@ def call(body) {
 
     contentRepository(body);
   }
+
+  def addPluginVersionTag(property, value) {
+      echo "Aadding a property <${property}> to pom.xml"
+      sh "find -type f -name 'pom.xml' | xargs sed -i -r '/<properties>/ a \\<fabric8-maven-plugin.version>${value}</fabric8-maven-plugin.version>'"
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: why not use `-exec ` e.g. 

```sh
find -type f -name pom.xml -exec sed -i -r '/<properties>/ a \\    <fabric8-maven-plugin.version>${value}</fabric8-maven-plugin.version>' {} \;
```

File: vars/mavenCanaryRelease.groovy [hunk 4]
```diff
@@ -66,3 +70,10 @@ def call(body) {
 
     contentRepository(body);
   }
+
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: Please add a comment explaining what this method tries to achieve
e.g. 

Given a pom.xml as 
```xml
<foo>
</foo>

it returns 
<foo>
  <bar>
  </bar>
<foo>
```

File: vars/mavenCanaryRelease.groovy [hunk 5]
```diff
@@ -66,3 +70,10 @@ def call(body) {
...
+  def addPluginVersionTag(property, value) {
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: How about we rename this to `patchFMPVersion`

File: vars/mavenCanaryRelease.groovy (hunk 3 above)
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: I am a bit against replacing **all** pom.xml and also running find since
- it can increase the build time since it has to traverse all files.
- it can create problems later on as we are changing all pom.xml and  the source would compile for them in their local env but not in our build and this will be too hard to debug.

How about we maintain a list of files to patch? 
e.g. 

```groovy
pomXmls = [
  './pom.xml', 
  './foobar/bar/pom.xml'
]
```

File: vars/mavenCanaryRelease.groovy [hunk 6]
```diff
@@ -66,3 +70,10 @@ def call(body) {
...
+      echo "Aadding a property <${property}> to pom.xml"
```
[the remark this answers is not in the document]
Comment (hrishin) [reply vars/mavenCanaryRelease.groovy]: fixed

File: vars/mavenCanaryRelease.groovy (hunk 4 above)
Comment (hrishin) [reply vars/mavenCanaryRelease.groovy]: fixed it

**Comment by hrishin** [comment]
@sthaha as per review I'm agreed that updating `pom.xml` using grep/sed is not an elegant way. It could do some unwanted side effects on `pom.xml`.
Looking at the urgency of this issue we could accept this patch, will file another issue to work on it.

File: vars/mavenCanaryRelease.groovy [hunk 7]
```diff
@@ -9,12 +9,16 @@ def call(body) {
 
     def flow = new io.fabric8.Fabric8Commands()
     def utils = new io.fabric8.Utils()
+    def pomFMPVersionKey = config.fmpVersionPropertyName ?: "fabric8-maven-plugin.version"
```
Comment (maxandersen) [inline vars/mavenCanaryRelease.groovy]: does this mean it will use the fmpversionproerty from users pom.xml if present and otherwise default to the specific version ?

**Comment by aslakknutsen** [comment]
Did you guys try/know/consider just calling the plugin from cli without touching the pom at all?

   mvn .... io.fabric8:fabric8-maven-plugin-build:$version:deploy

**Comment by bartoszmajsak** [comment]
@jaseemabid 

> This patch looks good to me, but shows some very deep flaws with our architecture and design.

Please document those flaws either as issues to fix here or in the context of **build.next** alongside with suggestions how to improve that. We have to make sure we won't face similar challenges in the future. This would be amazing contribution.

**Comment by hrishin** [comment]
> Did you guys try/know/consider just calling the plugin from cli without touching the pom at all?

@aslakknutsen we tried it. calling only `deploy` goal is not sufficient in that case. To deploy the application it needs to invoke at least `resource`, `package`, `build` and `deploy` goals. Calling these goals together generating resource and building an S2I image twice.

File: vars/mavenCanaryRelease.groovy (hunk 7 above)
Comment (hrishin) [reply vars/mavenCanaryRelease.groovy]: @maxandersen yes it uses fmpversionproerty from pom.xml. But its always going to use a specific version of FMP between [3.5.38 to 4.0.0](https://github.com/fabric8io/fabric8-pipeline-library/pull/392/files#diff-663252489f1c9712dbeb52401d084235R16) if [autoUpdateFMPVersion](https://github.com/fabric8io/fabric8-pipeline-library/pull/392/files#diff-663252489f1c9712dbeb52401d084235R12) flag is enabled

Comment (hrishin) [reply vars/mavenCanaryRelease.groovy]: dropping open ended version here, its not working for resolving plugin version.

File: vars/mavenCanaryRelease.groovy [hunk 8]
```diff
@@ -65,4 +69,41 @@ def call(body) {
...
 
     contentRepository(body);
-  }
+}
+
+def patchFMPVersion() {
+    def utils = new io.fabric8.Utils()
+    def pomModel = readMavenPom file: 'pom.xml'
+
+    if(pomModel.profiles) {
```
[the remark this answers is not in the document]
Comment (sthaha) [reply vars/mavenCanaryRelease.groovy]: IMHO, this is way too complicated than it need to be. lets refactor this a bit.

File: src/io/fabric8/Utils.groovy [hunk 9]
```diff
@@ -616,4 +616,31 @@ def isKubernetesPluginVersion013(){
...
+    int diff = Integer.valueOf(v1vals[i]).compareTo(Integer.valueOf(v2vals[i]));
+    return sigNum(diff) == -1
+  }
+
+  return sigNum(v1vals.length - v2vals.length) == -1
+}
+
+
+def sigNum(i) {
+  return i >> 31 | -i >>> 31
```
[the remark this answers is not in the document]
Comment (hrishin) [reply src/io/fabric8/Utils.groovy]: This method is not allowed on Jenkins sandbox

File: vars/mavenCanaryRelease.groovy [hunk 10]
```diff
@@ -65,4 +70,159 @@ def call(body) {
...
+}
+
+/**
+ * given versions strings v1 and v2 returns versions partitioned into
+ * an array of strings of equal length. e.g.
+ * "1.2", "3.4.5" returns [1, 2, 0], [3, 4, 5]
+ * "1.2.3-5", "3.4.5" returns [1, 2, 3, 15], [3, 4, 5]
+ */
+def partitionVersions(v1, v2) {
+    delim = '[\\.-]'
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: @hrishin just learned that without `def` the variable becomes something  close to a global variable; so we have to add `def` here for all var declarations. e.g. try this

```groovy

def f() {
  x = 1
}

f()
println x
```

File: vars/mavenCanaryRelease.groovy [hunk 11]
```diff
@@ -65,4 +70,159 @@ def call(body) {
...
+    for (int i=0; i < maxParts; i++){
+        if(v1Parts[i] != v2Parts[i]){
+            return v1Parts[i] - v2Parts[i]
+        }
+    }
+
+    return 0
+}
+
+def zeroFill(v, count) {
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: we need to document why we are doing this instread of just `[0] * num`; sandbox

File: vars/mavenCanaryRelease.groovy [hunk 12]
```diff
@@ -65,4 +70,159 @@ def call(body) {
...
+def patchFMPVersion() {
+    def pomModel = readMavenPom file: 'pom.xml'
+
+    if (!pomModel.profiles) {
+        return false
+    }
+
+    def updatedPlugin = false
+    for(profile in pomModel.profiles) {
+        if(!profile.id.equalsIgnoreCase("openshift") && !profile.build.plugins) {
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: would this work as expected? say profile.id is "x" then first condition becomes true and then checks if the profile has build plugins ... which is wrong. 

the `&&` must be `||` 
IMHO. it is ok to be not DRY for clarity 

e.g.

```groovy
if (!profile.equals("openshift") {
   continue
}

if (!profile.build.plugins) {
  continue
}
```

File: vars/mavenCanaryRelease.groovy [hunk 13]
```diff
@@ -65,4 +70,159 @@ def call(body) {
...
+            continue
+        }
+
+        for(plugin in profile.build.plugins) {
+            if(plugin.artifactId != "fabric8-maven-plugin") {
+                continue
+            }
+
+            if(plugin.version) {
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: we need to explain why we have else when the plugin has no version

File: vars/mavenCanaryRelease.groovy [hunk 14]
```diff
@@ -65,4 +70,159 @@ def call(body) {
...
+                if (compareVersions(plugin.version, "3.5.38") < 0) {
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: it is better to declare 3.5.38 as  const since it used at multiple places.

File: vars/mavenCanaryRelease.groovy [hunk 15]
```diff
@@ -65,4 +70,164 @@ def call(body) {
...
+
+    if (updatedPlugin) {
+        writeMavenPom model: pomModel
+    }
+
+    return updatedPlugin
+}
+
+/*
+* if v1 is greater than v2 returns false
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: this isn't true anymore

**Comment by hrishin** [comment]
> Could you please update the documentation of the method before merging?

done

> may want to rename patchBasedOnParentForPlugin to patchPluginBasedOnParent

done

> may want to rename patchBasedOnParentForProfile to patchParentProfile

done

I have tested this patch for all scenarios. It's working well now. Looks good for merge.

File: vars/mavenCanaryRelease.groovy [hunk 16]
```diff
@@ -65,4 +71,164 @@ def call(body) {
...
+    return updatedPlugin
+}
+
+/*
+* if v1 is greater than v2 returns +ve number
+* if v2 is greater than v1 returns -ve number
+* if v1 is equal to v2 return 0
+*/
+def compareVersions(v1, v2) {
+    (v1Parts, v2Parts) = partitionVersions(v1, v2)
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: missing def?

File: vars/mavenCanaryRelease.groovy [hunk 17]
```diff
@@ -65,4 +71,164 @@ def call(body) {
...
+    println v1Parts
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: do we still need println ?

File: vars/mavenCanaryRelease.groovy [hunk 18]
```diff
@@ -65,4 +71,164 @@ def call(body) {
...
+
+/**
+ * given versions strings v1 and v2 returns versions partitioned into
+ * an array of strings of equal length. e.g.
+ * "1.2", "3.4.5" returns [1, 2, 0], [3, 4, 5]
+ * "1.2.3-5", "3.4.5" returns [1, 2, 3, 15], [3, 4, 5]
+ */
+def partitionVersions(v1, v2) {
+    def delim = '[\\.-]'
+    v1Parts = v1.split(delim).collect { Integer.valueOf(it) }
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: def?

File: vars/mavenCanaryRelease.groovy [hunk 19]
```diff
@@ -65,4 +71,164 @@ def call(body) {
...
+    v2Parts = v2.split(delim).collect { Integer.valueOf(it) }
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: def

File: vars/mavenCanaryRelease.groovy [hunk 20]
```diff
@@ -65,4 +71,162 @@ def call(body) {
...
+}
+
+/*
+* if v1 is greater than v2 returns +ve number
+* if v2 is greater than v1 returns -ve number
+* if v1 is equal to v2 return 0
+*/
+def compareVersions(v1, v2) {
+    // not using def (v1Parts, v2Parts) = .. because UnsupportedOperationException: multiple assignments not supported
+    (v1Parts, v2Parts, maxParts) = partitionVersions(v1, v2)
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: why return maxParts, the method guarantees that both arrays are going to be same length, doesn't it?

File: vars/mavenCanaryRelease.groovy [hunk 21]
```diff
@@ -65,4 +71,162 @@ def call(body) {
...
+
+    for (int i=0; i < maxParts; i++){
+        if(v1Parts[i] != v2Parts[i]){
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: just noticed we can write this as:

```groovy

def diff = v1Parts[i] - v2Parts[i]
if (diff != 0) {
  return diff
}
```

File: vars/mavenCanaryRelease.groovy (hunk 20 above)
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: without def these could globals -right?

File: vars/mavenCanaryRelease.groovy [hunk 22]
```diff
@@ -9,10 +13,15 @@ def call(body) {
 
     def flow = new io.fabric8.Fabric8Commands()
     def utils = new io.fabric8.Utils()
-
+    def autoUpdateFMP = config.autoUpdateFabric8Plugin ?: true
     def skipTests = config.skipTests ?: false
+    FMP_STABLE_VERSION = "3.5.38"
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: does final outside the `call` method work?

File: vars/mavenCanaryRelease.groovy (hunk 20 above)
Comment (sthaha) [reply vars/mavenCanaryRelease.groovy]: How about

``` groovy
def versions = foobar()
def v1Parts = versions[0]
def v2Parts = versions[0]

```

File: vars/mavenCanaryRelease.groovy [hunk 23]
```diff
@@ -65,4 +71,162 @@ def call(body) {
...
+    def delim = '[\\.-]'
+    def v1Parts = v1.split(delim).collect { Integer.valueOf(it) }
+    def v2Parts = v2.split(delim).collect { Integer.valueOf(it) }
+
+    // make the versions equal by zero filling the array
+    def maxParts = Math.max(v1Parts.size(), v2Parts.size())
+    zeroFill(v1Parts, maxParts - v1Parts.size() )
+    zeroFill(v2Parts, maxParts - v2Parts.size() )
+
+    return [v1Parts, v2Parts, maxParts]
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: maxParts isn't needed

File: vars/mavenCanaryRelease.groovy [hunk 24]
```diff
@@ -65,4 +71,162 @@ def call(body) {
...
+        println "patching maven plugin for spring-boot-booster-parent v1.5.10-15"
+        plugin.version = FMP_STABLE_VERSION
+        return true;
+    }
+
+    return false;
+}
+
+def patchProfileBasedOnParent(pomModel) {
+    parent = pomModel.parent
```
Comment (sthaha) [inline vars/mavenCanaryRelease.groovy]: def

File: vars/mavenCanaryRelease.groovy (hunk 22 above)
Comment (hrishin) [reply vars/mavenCanaryRelease.groovy]: we tried but constant didn't worked
